### ISSUE TITLE
Mouse Over Html

### ISSUE THREAD

**Issue by andrewcartwright1** [sinelaw/HtmlTextBlock#1]
Hi,

I've been looking at this for a while, I like this alot but I'd like to change my mouse to use the hover mouse instead of the arrow mouse when I am over the html.

How would you go about doing this?

Many thanks,
Andrew

**Comment by sinelaw** [comment]
I'm not sure what you mean by "change my mouse to use the hover mouse"...

Do you mean changing the cursor (shape of mouse icon)? If yes, why not use [`:hover` in standard CSS](https://developer.mozilla.org/en-US/docs/Web/CSS/:hover) and set the [cursor](https://developer.mozilla.org/en-US/docs/Web/CSS/cursor)?

```
div:hover {
    cursor: pointer;
}
```

If you mean something else, please explain...

Thanks!

**Comment by andrewcartwright1** [comment]
I'm using this in a wpf application not html so css is out the question :(.

But yes that's what I mean

**Comment by sinelaw** [comment]
Right, sorry! I was confused with another project.

You want the mouse cursor to change when over anywhere in the HtmlTextBlock control? or over any html inside? or specifically over some part of the html that's inside?

**Comment by andrewcartwright1** [comment]
Haha no worries. Just over the html parts, I was playing around with some of the events available but could never get it to work.

**Comment by andrewcartwright1** [comment]
Sussed out that it does that, My mouse was getting locked as a pointer in another bit of my code aha.
